import ctypes,os,json,re,zipfile
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
root=Path(__file__).resolve().parents[1];os.chdir(root)
output=root/'preview/double-freedom-detailed-ribs-proposal.png';output.parent.mkdir(exist_ok=True)
d=ctypes.CDLL(r'C:\Program Files (x86)\Steam\steamapps\common\Helldivers 2\bin\lua51.dll');d.luaL_newstate.restype=ctypes.c_void_p;s=d.luaL_newstate()
for n in ['luaL_openlibs','lua_close']:getattr(d,n).argtypes=[ctypes.c_void_p]
d.luaL_loadstring.argtypes=[ctypes.c_void_p,ctypes.c_char_p];d.lua_pcall.argtypes=[ctypes.c_void_p,ctypes.c_int,ctypes.c_int,ctypes.c_int];d.lua_tolstring.argtypes=[ctypes.c_void_p,ctypes.c_int,ctypes.c_void_p];d.lua_tolstring.restype=ctypes.c_char_p;d.luaL_openlibs(s)
def run(lua):
 status=d.luaL_loadstring(s,lua.encode()) or d.lua_pcall(s,0,0,0)
 if status:raise RuntimeError(d.lua_tolstring(s,-1,None).decode())
init=(root/'tests/contracts.lua').read_text().split('local tests=0')[0]
run(init)


run("\nlocal state=assert(loadfile('preview/senator_cylinder_state_proposal.lua'))()\nlocal panel=assert(loadfile('preview/senator_cylinder_panel_proposal.lua'))()\nlocal function model(n,u) return {resource_hex='8d3d52a3b2f19402',id=1,unit_ref=u or 9,value=n,reserve=30,fire_mode='SEMI'} end\nlocal t=state.new();local expected={1,6,5,4,3,2,1}\nfor shot=0,6 do local m=model(6-shot);state.step(t,m);assert(m.cylinder_turns==shot and m.cylinder_bottom==expected[shot+1]);assert(shot==6 or m.cylinder_slots[m.cylinder_bottom]);local count=0;for _,v in ipairs(m.cylinder_slots) do if v then count=count+1 end end;assert(count==6-shot) end\nlocal m=model(1);state.step(t,m);assert(m.cylinder_bottom==1 and m.cylinder_slots[1]);m=model(6);state.step(t,m);for _,v in ipairs(m.cylinder_slots) do assert(v) end\nlocal jump=state.new();state.step(jump,model(6));m=model(3);state.step(jump,m);assert(m.cylinder_turns==3 and m.cylinder_bottom==4 and not m.cylinder_slots[1] and not m.cylinder_slots[6] and not m.cylinder_slots[5]);state.step(jump,model(6));assert(jump.bottom==4 and jump.turns==3)\nm=model(2,10);state.step(jump,m);assert(m.cylinder_turns==0 and m.cylinder_bottom==1);state.step(jump,nil);assert(not jump.key);m=model(7);state.step(jump,m);assert(not m.cylinder_slots)\nlocal total,maxcommands=0,0\nfor font in pairs(HUD.native_font_data.faces) do for _,scale in ipairs({.05,1,2}) do\n local cfg=HUD.config.new();cfg.font=font;local tracker=state.new()\n for _,n in ipairs({6,5,4,3,2,1,0,1,6}) do\n local m=model(n);state.step(tracker,m);local out=panel.compose(m,0,0,scale,1,cfg);maxcommands=math.max(maxcommands,#out);local seen={}\n for _,v in ipairs(out) do if v.senator_part=='projectile' then seen[v.senator_slot]=true end\n if v.senator_part then assert(v.x>=0 and v.x+v.w<=out[1].w+1e-6 and v.y>=0 and v.y+v.h<=out[1].h+1e-6) end end\n local count=0;for i=1,6 do if seen[i] then count=count+1 end;assert((seen[i]==true)==m.cylinder_slots[i]) end;assert(count==n)\n if n>0 then local angle=-math.pi/2-(m.cylinder_bottom-1)*math.pi/3+m.cylinder_angle;assert(math.abs(math.cos(angle))<1e-6 and math.abs(math.sin(angle)+1)<1e-6) end\n local world=HUD.world_style.prepare(out,{},{scale=1,font=font,placement_mode='manual'});local ratio=240/out[1].w\n for i,v in ipairs(out) do if v.senator_part then assert(math.abs(world[i].w-v.w*ratio)<1e-6 and math.abs(world[i].h-v.h*ratio)<1e-6) end end\n total=total+1\n end\nend end\nprint(total..' rotation/bottom/identity/count/native/world checks passed; max '..maxcommands..' commands')\n")
d.lua_close(s)
