from pathlib import Path
import json
from PIL import Image
root=Path('.')
sel=json.load(open('assets/fonts/runtime-selection.json'));cat=json.load(open('assets/fonts/catalog.json'))
lines=['-- Generated by tools/build_runtime_fonts.py; printable ASCII direct geometry.','return {'];manifest=[]
for family,count in sel['families']:
 entry=next(x for x in cat['families'] if x['family']==family)
 faces=[f for f in entry['faces'] if 'FontMono-Regular' in f['name']]
 if family=='Meslo':faces=[f for f in faces if f['name']=='MesloLGMNerdFontMono-Regular.ttf']
 face=faces[0];meta=json.load(open(root/'assets/fonts'/face['metrics']));img=Image.open(root/'assets/fonts'/face['atlas'])
 key=family.lower();cap=abs(meta['glyphs']['72']['bounds'][1])/2;em=cap*1.5
 lines.append('["'+key+'"]={em='+str(em)+',glyphs={')
 total=0
 for code,g in meta['glyphs'].items():
  x,y,w,h=g['cell'];tile=img.crop((x,y,x+w,y+h)).resize((w//2,h//2),Image.Resampling.LANCZOS)
  runs=[];active={}
  for yy in range(tile.height):
   segments=[];xx=0
   while xx<tile.width:
    if tile.getpixel((xx,yy))<128:xx+=1;continue
    start=xx
    while xx<tile.width and tile.getpixel((xx,yy))>=128:xx+=1
    segments.append((start,xx-start))
   nxt={}
   for a,b in segments:
    if (a,b) in active:
     r=active[(a,b)];r[3]+=1
    else:
     r=[a-meta['origin_x']/2,meta['baseline']/2-yy-1,b,1];runs.append(r)
    nxt[(a,b)]=r
   active=nxt
  # Runs were extended downward: move their bottom edge down as height grows.
  for r in runs:r[1]-=r[3]-1
  bounds=[min((r[0] for r in runs),default=0),min((r[1] for r in runs),default=0),max((r[0]+r[2] for r in runs),default=0),max((r[1]+r[3] for r in runs),default=0)]
  def arr(a):return '{'+','.join(str(v) for v in a)+'}'
  lines.append('['+code+']={advance='+str(g['advance']/2)+',bounds='+arr(bounds)+',runs={'+','.join(arr(r) for r in runs)+'}},')
  total+=len(runs)
 lines.append('}},');manifest.append({'id':key,'label':family+' Nerd Font','face':face['name'],'rectangles':total,'downloads':count})
lines.append('}')
(root/'src/nerd_font_data.lua').write_text('\n'.join(lines)+'\n')
(root/'assets/fonts/runtime-faces.json').write_text(json.dumps(manifest,indent=2))
print('Generated',len(manifest),'fonts',sum(x['rectangles'] for x in manifest),'glyph rectangles')
